WITH sale AS(
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES 
    WHERE SALES_DATE LIKE '2022-01-%'
    GROUP BY BOOK_ID
    ORDER BY BOOK_ID
) 

SELECT BOOK.AUTHOR_ID
    , AUTHOR.AUTHOR_NAME
    , BOOK.CATEGORY
    , SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK 
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN sale ON BOOK.BOOK_ID = sale.BOOK_ID
GROUP BY AUTHOR.AUTHOR_ID,AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID ASC
       , BOOK.CATEGORY DESC
