SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME,  b.MAX_FAVORITES FAVORITES
FROM REST_INFO a
JOIN(
SELECT MAX(FAVORITES) MAX_FAVORITES
FROM REST_INFO 
GROUP BY FOOD_TYPE
) b
ON a.FAVORITES = b.MAX_FAVORITES
GROUP BY a.FOOD_TYPE
ORDER BY a.FOOD_TYPE DESC
