-- 코드를 입력하세요
-- 2021년에 가입한 전체 회원 수
SELECT YEAR(sale.SALES_DATE) AS YEAR
     , MONTH(sale.SALES_DATE) AS MONTH 
     , COUNT(DISTINCT(sale.USER_ID)) AS PURCHASED_USERS
     , ROUND(COUNT(DISTINCT(sale.USER_ID))/(SELECT COUNT(USER_ID)
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE sale
JOIN USER_INFO user
ON sale.USER_ID = user.USER_ID
AND YEAR(user.JOINED) = 2021
GROUP BY MONTH(sale.SALES_DATE), YEAR(sale.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC