SELECT a.CAR_ID
, (
    CASE WHEN b.CAR_ID IS NOT NULL THEN '대여중'
    ELSE '대여 가능' END
)AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
LEFT JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE 
    GROUP BY CAR_ID
    ORDER BY CAR_ID DESC
) b
USING(CAR_ID)
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
