-- 코드를 입력하세요
SELECT 
      MEMBER_PROFILE.MEMBER_NAME
    , REST_REVIEW.REVIEW_TEXT
    , DATE_FORMAT(REST_REVIEW.REVIEW_DATE ,  "%Y-%m-%d")
FROM REST_REVIEW 
    JOIN MEMBER_PROFILE 
    ON REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
    WHERE MEMBER_PROFILE.MEMBER_ID = 
    (
        SELECT MEMBER_ID 
        FROM REST_REVIEW R 
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
    ORDER BY REST_REVIEW.REVIEW_DATE ASC, REST_REVIEW.REVIEW_TEXT ASC