-- 서브쿼리를 사용하여 2022년 8월부터 10월까지 총 대여 횟수가 5회 이상인 자동차를 필터링
WITH TotalRentals AS (
    SELECT 
        CAR_ID
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY 
        CAR_ID
    HAVING 
        COUNT(*) >= 5
)

-- 월별 자동차 대여 횟수를 계산하는 메인 쿼리
SELECT 
    EXTRACT(MONTH FROM START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    AND CAR_ID IN (SELECT CAR_ID FROM TotalRentals)
GROUP BY 
    EXTRACT(YEAR FROM START_DATE), EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY 
    MONTH ASC, 
    CAR_ID DESC;
