-- 코드를 작성해주세요
WITH TOP AS(
    SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO a
LEFT JOIN FISH_NAME_INFO b
USING (FISH_TYPE)
WHERE (a.FISH_TYPE, a.LENGTH) IN (SELECT *  FROM TOP)
ORDER BY a.ID