SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO a
LEFT JOIN FISH_NAME_INFO b
USING (FISH_TYPE)
WHERE (a.FISH_TYPE, a.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO
    GROUP BY FISH_TYPE)
ORDER BY a.ID